#!/usr/bin/with-contenv sh

set -e
source $HENCE_PREFIX/hence-utils.sh

set -- php-fpm -F

if [ ! "$(ls -A $HENCE_APP_VOL_PREFIX/conf)" ]; then
  generate_conf_files
fi

if [ -f ./setup ]
then
  ./setup
fi

chown -R $HENCE_APP_USER:$HENCE_APP_USER \
  $HENCE_APP_VOL_PREFIX/conf/ \
  $HENCE_APP_VOL_PREFIX/logs/ \
  /app || true

print_welcome_page

exec "$@"
