#!/bin/bash

export DOLLAR='$'
export VARNISH_HA_SERVERS=""
export VARNISH_HA_BACKENDS=""

if [ -z "${VARNISH_PORT}" ]
then
  export VARNISH_PORT=80
fi

if [ -z "${VARNISH_BACKEND_IP}" ]
then
  export VARNISH_BACKEND_IP=172.17.42.1
fi

if [ -z "${VARNISH_BACKEND_HOST_HEADER}" ]
then
  export VARNISH_BACKEND_HOST_HEADER=example.com
fi

if [ -z "${VARNISH_BACKEND_PORT}" ]
then
  export VARNISH_BACKEND_PORT=80
fi

if [ -z "${VARNISH_STORAGE_AMOUNT}" ]
then
  export VARNISH_STORAGE_AMOUNT=100m
fi

if [ -z "${VARNISH_SESS_TIMEOUT}" ]
then
  export VARNISH_SESS_TIMEOUT=20
fi

if [ -z "${VARNISH_CONSOLE_PORT}" ]
then
  export VARNISH_CONSOLE_PORT=2000
fi

if [ -z "${VARNISH_CONSOLE_SECRET}" ]
then
  export VARNISH_CONSOLE_SECRET=changeme
fi

if [ -z "${VARNISH_CONFIG_PRESET}" ]
then
  export VARNISH_CONFIG_PRESET=default
fi

if [ -z "${VARNISH_FIRST_BYTE_TIMEOUT}" ]
then
  export VARNISH_FIRST_BYTE_TIMEOUT=60s
fi

if [ -z "${VARNISH_PROBE_URL}" ]
then
  export VARNISH_PROBE_URL=/
fi

if [ -z "${VARNISH_PROBE_TIMEOUT}" ]
then
  export VARNISH_PROBE_TIMEOUT=2s
fi

if [ -z "${VARNISH_PROBE_INTERVAL}" ]
then
  export VARNISH_PROBE_INTERVAL=5s
fi

if [ -z "${VARNISH_PROBE_WINDOW}" ]
then
  export VARNISH_PROBE_WINDOW=8
fi

if [ -z "${VARNISH_PROBE_THRESHOLD}" ]
then
  export VARNISH_PROBE_THRESHOLD=3
fi

if [ -z "${VARNISH_HA_DIRECTOR_TYPE}" ]
then
  export VARNISH_HA_DIRECTOR_TYPE=round_robin
fi

if [ -z "${VARNISH_HA_DIRECTOR_BACKEND_ARG}" ]
then
  export VARNISH_HA_DIRECTOR_BACKEND_ARG=""
fi

# Create the secret file
if [ ! -f "$HENCE_APP_VOL_PREFIX/conf/secret" ]
then
  echo $VARNISH_CONSOLE_SECRET >> $HENCE_APP_VOL_PREFIX/conf/secret
fi

if [ -n "${VARNISH_RANCHER_HA}" ]
then
  BACKEND_COUNT=`curl -s http://rancher-metadata/2015-12-19/containers | grep -c ${VARNISH_BACKEND_IP}`
  i=1
  export VARNISH_HA_SERVERS=""

  rm -f $HENCE_APP_VOL_PREFIX/conf/backends
  touch $HENCE_APP_VOL_PREFIX/conf/backends

  while [[ $i -le $BACKEND_COUNT ]]
  do
    export INDEX=$((i-1))
    i=$((i+1))

    export IP=`curl -s http://rancher-metadata/2015-12-19/services/app-lb/containers/$INDEX/primary_ip`

    envsubst < $HENCE_APP_VOL_PREFIX/conf/templates/backend.tmpl >> $HENCE_APP_VOL_PREFIX/conf/backends

    if [ "$VARNISH_HA_DIRECTOR_TYPE" = "round_robin" ]
    then
      WEIGHT_ARG=""
    else
      WEIGHT_ARG=", 1.0"
    fi

    VARNISH_HA_SERVERS="${VARNISH_HA_SERVERS}
    vdir.add_backend(server$INDEX$WEIGHT_ARG);"

  done
fi


envsubst < $HENCE_APP_VOL_PREFIX/conf/presets/$VARNISH_CONFIG_PRESET.vcl.tmpl > $HENCE_APP_VOL_PREFIX/conf/default.vcl
