#!/usr/bin/with-contenv sh

set -e
source $HENCE_PREFIX/hence-utils.sh

set -- mysqld

if [ ! "$(ls -A $HENCE_APP_VOL_PREFIX/conf)" ]; then
  generate_conf_files
fi

if [ -f ./setup ] && [ ! -f $HENCE_APP_VOL_PREFIX/conf/my.cnf ]
then
  ./setup
fi

PROGRAM_OPTIONS="--defaults-file=$HENCE_APP_DIR/conf/my.cnf --log-error=$HENCE_APP_DIR/logs/mysqld.log --basedir=$HENCE_APP_DIR --datadir=$HENCE_APP_DIR/data --plugin-dir=$HENCE_APP_DIR/lib/plugin --user=$HENCE_APP_USER --socket=$HENCE_APP_DIR/tmp/mysql.sock --lower-case-table-names=1 $EXTRA_OPTIONS"
set -- $@ $PROGRAM_OPTIONS

mkdir -p $HENCE_APP_DIR/tmp
chown -R $HENCE_APP_USER:$HENCE_APP_USER $HENCE_APP_DIR/tmp || true

if [ ! -d $HENCE_APP_VOL_PREFIX/data/mysql ]; then

  set -- "$@" --init-file=/tmp/init_mysql.sql

  initialize_database

  create_custom_database

  create_mysql_user

  print_app_credentials $HENCE_APP_NAME $MARIADB_USER `print_mysql_password` `print_mysql_database`
else
  print_container_already_initialized $HENCE_APP_NAME
fi

chown -R $HENCE_APP_USER:$HENCE_APP_USER \
  $HENCE_APP_VOL_PREFIX/conf/ \
  $HENCE_APP_VOL_PREFIX/logs/ \
  $HENCE_APP_VOL_PREFIX/data/ || true


EFIFO=/var/run/s6/mysql-error-log-fifo
GFIFO=/var/run/s6/mysql-general-log-fifo
SQFIFO=/var/run/s6/mysql-slow-query-log-fifo

set -- "$@" --general-log-file=${EFIFO}
set -- "$@" --slow-query-log-file=${EFIFO}

print_welcome_page

exec "$@"
