#!/usr/bin/with-contenv sh



set -e
source $HENCE_PREFIX/hence-utils.sh

print_welcome_page

set -- mysqld

if [ ! "$(ls -A $HENCE_APP_VOL_PREFIX/conf)" ]; then
  generate_conf_files
fi

if [ -f ./setup ] && [ ! -f $HENCE_APP_VOL_PREFIX/conf/my.cnf ]
then
  ./setup
fi

set -- $@ $PROGRAM_OPTIONS
mkdir -p $HENCE_APP_DIR/tmp
chown -R $HENCE_APP_USER:$HENCE_APP_USER $HENCE_APP_DIR/tmp || true

if [ ! -d $HENCE_APP_VOL_PREFIX/data/mysql ]; then

  set -- "$@" --init-file=/tmp/init_mysql.sql

  initialize_database

  create_custom_database

  create_mysql_user

  print_app_credentials $HENCE_APP_NAME $MARIADB_USER `print_mysql_password` `print_mysql_database`
else
  print_container_already_initialized $HENCE_APP_NAME
fi

chown -R $HENCE_APP_USER:$HENCE_APP_USER \
  $HENCE_APP_VOL_PREFIX/conf/ \
  $HENCE_APP_VOL_PREFIX/logs/ \
  $HENCE_APP_VOL_PREFIX/data/ || true


# multisubstitute
# {
#   define efifo /var/run/s6/mysql-error-log-fifo
#   define gfifo /var/run/s6/mysql-general-log-fifo
#   define sqfifo /var/run/s6/mysql-slow-query-log-fifo
#   import -u HENCE_PREFIX
# }

# redirfd -wnb 2 ${efifo}

# trap -x
# {
#   term { mysqladmin -u root shutdown }
# }

EFIFO=/var/run/s6/mysql-error-log-fifo
GFIFO=/var/run/s6/mysql-general-log-fifo
SQFIFO=/var/run/s6/mysql-slow-query-log-fifo

# mysqld --general-log-file=${gfifo} --slow-query-log-file=${sqfifo}
# mysqld
# exec "$@ --general-log-file=${gfifo} --slow-query-log-file=${sqfifo}"
exec "$@"
# exec su $HENCE_USER -c "$@ $PROGRAM_OPTIONS"
