#!/usr/bin/with-contenv sh

set -e
source $HENCE_PREFIX/hence-utils.sh

set -- /opt/solr/bin/solr

set -- "$@" -f

if [ ! "$(ls -A $HENCE_APP_VOL_PREFIX/conf)" ] && [ -z "${CONFIG_PRESET}" ] ; then
  generate_conf_files
  export CONFIG_PRESET_PATH=basic
fi

if [ -f ./setup ]
then
  ./setup
fi

chown -R $HENCE_APP_USER:$HENCE_APP_USER \
  $HENCE_APP_VOL_PREFIX/logs/ \
  $HENCE_APP_VOL_PREFIX/conf/ \
  /opt/solr \
  /opt/$SOLR || true

print_welcome_page

exec "$@"
