#!/bin/bash

declare -x CONFIG_PRESET_PATH

if [ -z "${CONFIG_PRESET_PATH}" ]
then
  CONFIG_PRESET_PATH=default
fi

create_core_properties_file() {
  mkdir -p $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH

  CORE_PROPERTIES_FILE=$HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH/core.properties

  if [ ! -f $CORE_PROPERTIES_FILE ]
  then
    touch $CORE_PROPERTIES_FILE
    echo "name=$CONFIG_PRESET_PATH" > $CORE_PROPERTIES_FILE
    echo "dataDir=../../../../hence/solr/data/$CONFIG_PRESET_PATH" >> $CORE_PROPERTIES_FILE

    mkdir $HENCE_APP_VOL_PREFIX/data/$CONFIG_PRESET_PATH
  fi
}

create_core_properties_file

if [ -n "${CONFIG_PRESET}" ]
then
  cp -R /etc/solr/presets/$CONFIG_PRESET $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH/conf
  ln -s $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH /opt/solr/server/solr/$CONFIG_PRESET_PATH
else
  if [ -n "$(ls -A $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH)" ] && [ ! ]
  then
    ln -s $HENCE_APP_DIR/conf/$CONFIG_PRESET_PATH /opt/solr/server/solr/$CONFIG_PRESET_PATH
  fi
fi
