#!/bin/bash

declare -x CONFIG_PRESET_PATH

if [ -z "${CONFIG_PRESET_PATH}" ]
then
  CONFIG_PRESET_PATH=default
fi

create_core_properties_file() {
  mkdir -p $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH

  if [ ! -f $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH/core.properties ]
  then
    touch $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH/core.properties
    echo "name=$CONFIG_PRESET_PATH" > $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH/core.properties
  fi
}

create_core_properties_file

if [ -n "${CONFIG_PRESET}" ]
then
  cp -R /etc/solr/presets/$CONFIG_PRESET $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH/conf
  ln -s $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH /opt/solr/server/solr/$CONFIG_PRESET_PATH

else
  if [ -n "$(ls -A $HENCE_APP_VOL_PREFIX/conf/$CONFIG_PRESET_PATH)" ] && [ ! ]
  then
    ln -s $HENCE_APP_DIR/conf/$CONFIG_PRESET_PATH /opt/solr/server/solr/$CONFIG_PRESET_PATH
  fi
fi
