#!/usr/bin/with-contenv sh

set -e
source $HENCE_PREFIX/hence-utils.sh

print_welcome_page

set -- nginx

set -- "$@" -c $HENCE_APP_VOL_PREFIX/conf/nginx.conf

if [ ! "$(ls -A $HENCE_APP_VOL_PREFIX/conf)" ]; then
  generate_conf_files
fi

if [ -f ./setup ] && [ ! -f $HENCE_APP_VOL_PREFIX/conf/nginx.conf ]
then
  ./setup
fi

if [ ! "$(ls -A /app)" ]; then
  cp -r $HENCE_APP_DIR/html.defaults/* /app
fi

chown -R $HENCE_APP_USER:$HENCE_APP_USER \
  $HENCE_APP_VOL_PREFIX/logs/ \
  $HENCE_APP_VOL_PREFIX/conf/ \
  /app || true

exec "$@"
