#!/bin/bash

export DOLLAR="$" # Needed to keep envsubst from destroying nginx variables in conf.tmpl files
declare -x NGINX_PHP_ALIAS
declare -x NGINX_PROXY_PATH
declare -x NGINX_PROXY_HOST
declare -x NGINX_PROXY_PORT
declare -x NGINX_SSL_INCLUDE
declare -x NGINX_SSL_CERT_FILE
declare -x NGINX_SSL_CERT_KEY_FILE
declare -x NGINX_FASTCGI_READ_TIMEOUT
declare -x NGINX_FASTCGI_IGNORE_CLIENT_ABORT
declare -x NGINX_CLIENT_MAX_BODY_SIZE
declare -x NGINX_CLIENT_BODY_BUFFER_SIZE
declare -x NGINX_HTPASSWD_INCLUDE
declare -x NGINX_HTPASSWD_USER
declare -x NGINX_HTPASSWD_PASSWORD
declare -x NGINX_HTPASSWD_PASSWORD_ENCRYPTED
declare -x NGINX_DOMAIN_REDIRECT
declare -x NGINX_REDIRECT_TYPE
declare -x NGINX_STATUS_INCLUDE
declare -x NGINX_APP_CHOWN_EXCLUSIONS_GLOB

if [ -z "${NGINX_PHP_ALIAS}" ]
then
  NGINX_PHP_ALIAS_NOT_PROVIDED=true
  NGINX_PHP_ALIAS=php
fi

if [ -z "${NGINX_PROXY_PATH}" ]
then
  NGINX_PROXY_PATH=rest/api
fi

if [ -z "${NGINX_PROXY_HOST}" ]
then
  NGINX_PROXY_HOST=localhost
fi

if [ -z "${NGINX_PROXY_PORT}" ]
then
  NGINX_PROXY_PORT=3000
fi

if [ -z "${NGINX_SSL_INCLUDE}" ]
then
  NGINX_SSL_INCLUDE=""
fi

if [ -z "${NGINX_SSL_CERT_FILE}" ]
then
  NGINX_SSL_CERT_FILE=""
fi

if [ -z "${NGINX_SSL_CERT_KEY_FILE}" ]
then
  NGINX_SSL_CERT_KEY_FILE=""
fi

if [ -z "${NGINX_FASTCGI_READ_TIMEOUT}" ]
then
  NGINX_FASTCGI_READ_TIMEOUT=300
fi

if [ -z "${NGINX_FASTCGI_IGNORE_CLIENT_ABORT}" ]
then
  NGINX_FASTCGI_IGNORE_CLIENT_ABORT=off
fi

if [ -z "${NGINX_CLIENT_MAX_BODY_SIZE}" ]
then
  NGINX_CLIENT_MAX_BODY_SIZE=128m
fi

if [ -z "${NGINX_CLIENT_BODY_BUFFER_SIZE}" ]
then
  NGINX_CLIENT_BODY_BUFFER_SIZE=128k
fi

if [ -z "${NGINX_HTPASSWD_USER}" ]
then
  NGINX_HTPASSWD_USER=hence
fi

if [ -z "${NGINX_HTPASSWD_PASSWORD}" ]
then
  NGINX_HTPASSWD_PASSWORD=access
fi

if [ -z "${NGINX_HTPASSWD_INCLUDE}" ]
then
  NGINX_HTPASSWD_INCLUDE=""
fi

if [ -z "${NGINX_DOMAIN_REDIRECT}" ]
then
  NGINX_DOMAIN_REDIRECT=""
fi

if [ -z "${NGINX_REDIRECT_TYPE}" ]
then
  NGINX_REDIRECT_TYPE="302"
fi

if [ -z "${NGINX_STATUS_INCLUDE}" ]
then
  NGINX_STATUS_INCLUDE=""
fi

if [ -z "${NGINX_APP_CHOWN_EXCLUSIONS_GLOB}" ]
then
  NGINX_APP_CHOWN_EXCLUSIONS_GLOB=""
fi

# Resolve php alias if provided to actual IP.  Needed for HA setups with sidekicks to avoid race condtion errors.
if [ -z "$NGINX_PHP_ALIAS_NOT_PROVIDED" ]
then
  until ping -c 1 $NGINX_PHP_ALIAS
  do
    echo "Trying to connect with $NGINX_PHP_ALIAS..."
  done
  NGINX_PHP_ALIAS=`ping -q -c 1 -t 1 $NGINX_PHP_ALIAS | grep -m 1 PING | cut -d "(" -f2 | cut -d ")" -f1`
fi

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

counter=0

if [ "${NGINX_PHP_RANCHER_SIDEKICK}" = "1" ]
then
  until valid_ip $NGINX_PHP_ALIAS
  do
    echo "Trying to get IP of Rancher PHP sidekick..."
    DEPLOYMENT_UNIT=`curl -s http://rancher-metadata.rancher.internal/latest/self/container/labels/io.rancher.service.deployment.unit`
    SERVICE_INDEX=`curl -s http://rancher-metadata.rancher.internal/latest/self/container/service_index`
    SERVICE_NAME=`curl -s http://rancher-metadata.rancher.internal/latest/self/container/service_name`
    STACK_NAME=`curl -s http://rancher-metadata.rancher.internal/latest/self/container/stack_name`
    PHP_SIDEKICK_NAME=`curl -s http://rancher-metadata.rancher.internal/latest/containers | grep "${STACK_NAME}_${SERVICE_NAME}" | grep php | grep "\_$SERVICE_INDEX$" | tr '=' "\n" | sed -n '2p'`
    PHP_SIDEKICK_DEPLOYMENT_UNIT=`curl -s http://rancher-metadata.rancher.internal/latest/containers/$PHP_SIDEKICK_NAME/labels/io.rancher.service.deployment.unit`

    if [ -n "$PHP_SIDEKICK_DEPLOYMENT_UNIT" -a  "$PHP_SIDEKICK_DEPLOYMENT_UNIT" = "$DEPLOYMENT_UNIT" ]
    then
      NGINX_PHP_ALIAS=`curl -s http://rancher-metadata.rancher.internal/latest/containers/$PHP_SIDEKICK_NAME/primary_ip`
      echo "$NGINX_PHP_ALIAS set as php backend service"
    else
      counter=$((counter+1))
      sleep 2

      if [[ "$counter" -gt 30 ]]; then
        s6-svscanctl -t /var/run/s6/services
      fi
    fi
  done
fi

chown -R $HENCE_APP_USER:www-data \
  /var/lib/nginx

if [ -n "${NGINX_CONFIG_PRESET}" ]
then
  sed -i "s/presets\/default/presets\/${NGINX_CONFIG_PRESET}/" $HENCE_APP_VOL_PREFIX/conf/nginx.conf.tmpl

  rm -f $HENCE_APP_VOL_PREFIX/conf/presets/$NGINX_CONFIG_PRESET.conf
  envsubst < $HENCE_APP_VOL_PREFIX/conf/presets/$NGINX_CONFIG_PRESET.conf.tmpl > $HENCE_APP_VOL_PREFIX/conf/presets/$NGINX_CONFIG_PRESET.conf
fi

if [ "${NGINX_HTPASSWD_ENABLE}" = "1" ]
then
  NGINX_HTPASSWD_INCLUDE="include $HENCE_APP_VOL_PREFIX/conf/htpasswd.conf;"

  rm -f $HENCE_APP_VOL_PREFIX/conf/htpasswd.conf $HENCE_APP_VOL_PREFIX/conf/.passwd
  envsubst < $HENCE_APP_VOL_PREFIX/conf/htpasswd.conf.tmpl > $HENCE_APP_VOL_PREFIX/conf/htpasswd.conf
  envsubst < $HENCE_APP_VOL_PREFIX/conf/.passwd.tmpl > $HENCE_APP_VOL_PREFIX/conf/.passwd

  NGINX_HTPASSWD_PASSWORD_ENCRYPTED=`openssl passwd -apr1 -in $HENCE_APP_VOL_PREFIX/conf/.passwd`

  rm $HENCE_APP_VOL_PREFIX/conf/.htpasswd
  envsubst < $HENCE_APP_VOL_PREFIX/conf/.htpasswd.tmpl > $HENCE_APP_VOL_PREFIX/conf/.htpasswd
fi

if [ "${NGINX_SSL_ENABLE}" = "1" ]
then
  NGINX_SSL_INCLUDE="include $HENCE_APP_VOL_PREFIX/conf/presets/ssl.conf;"

  rm -f $HENCE_APP_VOL_PREFIX/conf/presets/ssl.conf
  envsubst < $HENCE_APP_VOL_PREFIX/conf/presets/ssl.conf.tmpl > $HENCE_APP_VOL_PREFIX/conf/presets/ssl.conf
fi

if [ "${NGINX_STATUS_ENABLE}" = "1" ]
then
  NGINX_STATUS_INCLUDE="include $HENCE_APP_VOL_PREFIX/conf/presets/status.conf;"

  rm -f $HENCE_APP_VOL_PREFIX/conf/presets/status.conf
  envsubst < $HENCE_APP_VOL_PREFIX/conf/presets/status.conf.tmpl > $HENCE_APP_VOL_PREFIX/conf/presets/status.conf
fi

sed -i "s/\$NGINX_STATUS_INCLUDE/${NGINX_STATUS_INCLUDE}/" $HENCE_APP_VOL_PREFIX/conf/nginx.conf.tmpl
sed -i "s/\$NGINX_HTPASSWD_INCLUDE/${NGINX_HTPASSWD_INCLUDE}/" $HENCE_APP_VOL_PREFIX/conf/nginx.conf.tmpl
sed -i "s/\$NGINX_SSL_INCLUDE/${NGINX_SSL_INCLUDE}/" $HENCE_APP_VOL_PREFIX/conf/nginx.conf.tmpl

rm -f $HENCE_APP_VOL_PREFIX/conf/nginx.conf
envsubst < $HENCE_APP_VOL_PREFIX/conf/nginx.conf.tmpl > $HENCE_APP_VOL_PREFIX/conf/nginx.conf
